# Generated by Django 5.1.6 on 2025-03-25 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquestioncategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='questionvariant',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionvariant',
            name='is_correct',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='correctquestion',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_correct_question'),
        ),
        migrations.AddConstraint(
            model_name='incorrectquestion',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_incorrect_question'),
        ),
        migrations.AddConstraint(
            model_name='savedquestion',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_saved_question'),
        ),
        migrations.AddConstraint(
            model_name='userquestioncategory',
            constraint=models.UniqueConstraint(fields=('user', 'question_category'), name='unique_user_question_category'),
        ),
    ]
