services:
  postgres_db:
    image: postgres:17
    container_name: my_auto_db
    networks:
      - auto_network
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - auto_network

  web:
    build:
      context: .
    image: auto_school
    container_name: my_auto
    command: ["/wait-db.sh", "postgres_db","5432", "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      - .:/var/www/auto
    networks:
      - auto_network

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A config worker --loglevel=info
    depends_on:
      - web
      - redis
    networks:
      - auto_network

  celery_beat:
    build:
      context: .
    container_name: celery-beat
    command: celery -A config beat --loglevel=info
    depends_on:
      - web
      - redis
      - celery
    networks:
      - auto_network

networks:
  auto_network:
volumes:
  db_data:
  redis_data: