# Generated by Django 5.1.6 on 2025-03-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roadsigns/images/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='roadsign',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='roadsign',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadsigns.roadsign', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='roadsign',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='roadsign',
            unique_together={('parent', 'ordering')},
        ),
    ]
