# Generated by Django 5.1.6 on 2025-03-24 20:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_initial'),
        ('lessons', '0004_alter_chapter_image_alter_lesson_chapter_and_more'),
        ('quizzes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_percent',
            field=models.BooleanField(default=False, verbose_name='Is percent'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='general',
            name='user_code_discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='level',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Coins'),
        ),
        migrations.AlterField(
            model_name='level',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/images/%Y/%m/%d/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='report',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(max_length=100, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('typo', 'Typo'), ('dontunderstand', 'Dontunderstand'), ('image_video', 'Image Video'), ('factual_error', 'Factual Error'), ('other', 'Other')], max_length=100, verbose_name='Report type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
