# Generated by Django 5.1.6 on 2025-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
