# Generated by Django 5.1.6 on 2025-03-11 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_initial'),
        ('notifications', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customnotification',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.discount'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='friend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.level'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.order'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='custom_notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_notifications', to='notifications.customnotification'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='system_notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sys_notifications', to='notifications.systemnotification'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
